### ISSUE TITLE
Configuration Validation 

### ISSUE THREAD

**Issue by BIoob** [realthk/asyncpioneer#14]
When I add  the code to my configuration.yaml my configuration validation fails.
This is what im using in my yaml to test if it works:

```
media_player:
- platform: asyncpioneer
  host: 192.168.0.115
  port: 8102
```

I added both .py files to /custom_components/asyncpioneer/ (in /homeassistant/ which is my /config folder).

Im new to this and a bit confused what I am doing wrong.

Should "asyncpioneer" show up as a media player entity like it does when I use the[ Pioneer](https://www.home-assistant.io/integrations/pioneer/) plugin? Cause it doesn't.

Any help is appreciated.
