### ISSUE TITLE
No conection on Pioneer VSX-930/SYXEV8 HDZone

### ISSUE THREAD

**Issue by user0x01** [realthk/asyncpioneer#15]
One port for Main and HDZone doesn't work. 

Workaround:
I define ports 49152,49153,49154 and add _zone_index to CONF_PORT

```
pioneer_z = PioneerDevice(
                hass,
                config.get(CONF_NAME) + "_" + zone,
                config.get(CONF_HOST),
                str(int(config.get(CONF_PORT)) + CONF_VALID_ZONES.index(zone)), ## every instance need its own port
                config.get(CONF_SERIAL_BRIDGE),
                config.get(CONF_DISABLED_SOURCES),
                config.get(CONF_LAST_RADIO_STATION),
                config.get(CONF_RADIO_STATIONS),
                zone,
                hasZones
                )
```

**Comment by glassbase** [comment]
All new Pioneer works with official Onkyo component. Why not use that? Onkyo bought Pioneer a few years ago. 
https://www.home-assistant.io/integrations/onkyo

edit - oh it doesn’t support zones

**Comment by user0x01** [comment]
Asyncpioneer works good. but only with a separate port for zones.  
Much better than the terrible ControlAV5 app

I miss only the service media_player.pioneer_select_favorites

**Comment by lakee911** [comment]
> 
> Workaround:
> I define ports 49152,49153,49154 

Can you share this piece of code too, please?

**Comment by lakee911** [comment]
I made the change w/ the code you provided and it clears up a no connection issue. However, I piped this into Node Red to sniff the telnet commands and it never actually sends the Zone2 command, despite listing in DEBUG that it does. Odd.

**Comment by lakee911** [comment]
Can anyone please help?

**Comment by user0x01** [comment]
here is my code: https://github.com/user0x01/asyncpioneer/blob/user0x01-patch-1/media_player.py

here the pioneer part of config.yaml
```
media_player:
  - platform: pioneer
    host: 192.168.1.11
    # 192.168.11.31
    port: 49152
    disabled_sources:
      - "MEDIA SERVER"
      - "CD"
      - "TUNER"
      - "iPod/USB"
      - "CD"
    zones:
      - zone: 'HDZone'
        name: HDZone
```

Under http://192.168.1.11/1000/port_number.asp
set port1: 49152, ports2: 49153, ports3: 49154.
