### ISSUE TITLE
Please help me with the speakers A+B

### ISSUE THREAD

**Issue by leodirob** [realthk/asyncpioneer#18]
Hi! Thank you for your Async Pioneer AV amp. I love it!
I'm a beginner in HA and  I'm sorry if my question may be trivial.
My VSX 923 works well in HA.
I would like to activate the A, B, and A+B buttons on  Mini Media Player like in your example.
https://user-images.githubusercontent.com/5654575/53702516-1f760700-3e08-11e9-900b-435edf7fbfa7.png

But I don't understand where I haven to paste your code.
If I put it in configuration.yaml he system gives me an error.

Can You Help Me?

**Comment by realthk** [comment]
It's very easy, just create scripts for every mode in scripts.yaml:
```
"speaker_a":
  alias: Select speaker A
  sequence:
    - service: media_player.pioneer_select_speaker
      data:
        entity_id: media_player.pioneer_avr
        speaker: "A"

"speaker_b":
  alias: Select speaker B
  sequence:
    - service: media_player.pioneer_select_speaker
      data:
        entity_id: media_player.pioneer_avr
        speaker: "B"

"speaker_a_b":
  alias: Select speaker A+B
  sequence:
    - service: media_player.pioneer_select_speaker
      data:
        entity_id: media_player.pioneer_avr
        speaker: "A+B"
```

and setup Mini Mediaplayer buttons for these (editing the config of this card in HA UI):

```
entity: media_player.pioneer_avr
info: scroll
shortcuts:
  buttons:
    - icon: 'mdi:speaker-wireless'
      id: script.speaker_a
      name: Speaker A
      type: script
    - icon: 'mdi:speaker-wireless'
      id: script.speaker_b
      name: Speaker B
      type: script
    - icon: 'mdi:speaker-wireless'
      id: script.speaker_a_b
      name: Speaker A+B
      type: script
  hide_when_off: true
source: full
type: 'custom:mini-media-player'
```

For additional features, check [Mini Media Player](https://github.com/kalkih/mini-media-player)
