### ISSUE TITLE
Support for volume bar on dB scale

### ISSUE THREAD

**Issue by tiagofreire-pt** [realthk/asyncpioneer#4]
The dB scale has a relation between steps (000 to 185), as:

dB(STEP) = 0.5 * STEP - 80.5 [dB]
or
STEP(dB) = 2 * dB + 161 [steps]

I'm interested on having the volume bar with dB scale instead of steps one. This could also be configured on the yaml with something similiar with:

```
media_player:
- platform: asyncpioneer
  host: 192.168.8.121
  port: 8102
  volume_scale: 'dB'
# OR
  volume_scale: 'steps'
```

This feature is supported and displayed by the VSX-924, as the dB scale is limited between:

000VL == "--- min"
001VL == -80,5dB
002VL == -80 dB
185VL == +12 dB
